version: "3.9"
   
services:
  db:
    volumes:
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=poppy
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    image: mysql:latest
    ports:
      - '3306:3306'
    expose:
      - 3306
  web:
    build: .
    image: sqlpad/sqlpad:latest
    links:
      - "db:database"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - SQLPAD_ADMIN=admin@sqlpad.com
      - SQLPAD_ADMIN_PASSWORD=sqlpassword
volumes:
  my-db:
